blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_category/', views.add_category, name='add_category'),
    path('create/', views.BlogCreateView.as_view(), name='create_blog'),
    path('<int:pk>/', views.BLogDetailView.as_view(), name='blog_details'),
    path('<int:pk>/update/', views.BlogUpdateView.as_view(), name='update_blog'),
    path('<int:pk>/delete/', views.BlogDeleteView.as_view(), name='delete_blog'),
    path('<str:username>/<str:category>/', views.UserBlogListView.as_view(), name='user_blogs'),
    path('<int:pk>/<str:opinion>/vote', views.BlogVoteView.as_view(), name='vote_blog'),
    path('category/<str:category>/view', views.CategoryBlogListView.as_view(), name='category_blogs'),
    path('comment/<int:pk>/add', views.BlogCommentCreateView.as_view(), name='add_comment'),
    path('comment/<int:pk>/update', views.BlogCommentUpdateView.as_view(), name='update_comment'),
    path('comment/<int:pk>/delete', views.BlogCommentDeleteView.as_view(), name='delete_comment'),
    path('comment/<int:pk>/<str:opinion>/vote', views.BlogCommentVoteView.as_view(), name='vote_blog_comment'),
]

support/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('issues', views.IssueListView.as_view(), name='myissues'),
    path('queries', views.QueryListView.as_view(), name='myqueries'),
    path('feedbacks', views.FeedbackListView.as_view(), name='myfeedbacks'),
    path('issue/submit', views.IssueCreateView.as_view(), name='submit_issue'),
    path('query/submit', views.QueryCreateView.as_view(), name='submit_query'),
    path('feedback/submit', views.FeedbackCreateView.as_view(), name='submit_feedback'),
    path('issue/<int:pk>/', views.IssueDetailView.as_view(), name='issue_details'),
    path('query/<int:pk>/', views.QueryDetailView.as_view(), name='query_details'),
    path('feedback/<int:pk>/', views.FeedbackDetailView.as_view(), name='feedback_details'),
    path('issue/<int:pk>/update', views.IssueUpdateView.as_view(), name='update_issue'),
    path('query/<int:pk>/update', views.QueryUpdateView.as_view(), name='update_query'),
    path('feedback/<int:pk>/update', views.FeedbackUpdateView.as_view(), name='update_feedback'),
    path('issue/<int:pk>/comment/add', views.IssueCommentCreateView.as_view(), name='add_issue_comment'),
    path('query/<int:pk>/comment/add', views.QueryCommentCreateView.as_view(), name='add_query_comment'),
    path('feedback/<int:pk>/comment/add', views.FeedbackCommentCreateView.as_view(), name='add_feedback_comment'),
]

unifieddashboard/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

handler404 = views.handle_404
handler403 = views.handle_403
handler500 = views.handle_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BlogListView.as_view(), name='home'),
    path('accounts/', include('users.urls')),
    path('verifications/', include('verification.urls')),
    path('blogs/', include('blogs.urls')),
    path('services/', include('support.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/models.py
import os
import re
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
def upload_issue_images(instance, filename):
    file_ext = os.path.splitext(filename)[-1]
    ref_title = re.sub('\W', '', instance.short_description)[:50]
    file_name = f"{instance.author.username}_{ref_title}_{instance.create_date.timestamp()}" + file_ext
    return os.path.join('support', instance.category.name.replace(' ', ''), file_name)


def default_user():
    return User.objects.get(username='deleted')


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Platform(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=10)

    @classmethod
    def get_default_status(cls):
        status, created = cls.objects.get_or_create(name='OPEN')
        return status.pk

    def __str__(self):
        return self.name


class Priority(models.Model):
    name = models.CharField(max_length=10)

    @classmethod
    def get_default_priority(cls):
        priority, created = cls.objects.get_or_create(name='LOW')
        return priority.pk

    def __str__(self):
        return self.name


class Issue(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=default_user)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    platform = models.ForeignKey(Platform, on_delete=models.RESTRICT)
    priority = models.ForeignKey(Priority, on_delete=models.RESTRICT, default=Priority.get_default_priority)
    short_description = models.CharField(max_length=100)
    long_description = models.TextField()
    image = models.ImageField(upload_to=upload_issue_images, blank=True)
    create_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(blank=True, null=True)
    close_date = models.DateTimeField(blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.RESTRICT, default=Status.get_default_status)

    def __str__(self):
        return f"{self.category} - {self.short_description}"

    # def save(self, *args, **kwargs):
    #     try:
    #         this = Issue.objects.get(id=self.id)
    #         if this.image != self.image:
    #             this.image.delete()
    #     except:
    #         pass
    #     super(Issue, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('home')


class IssueComment(models.Model):
    comment = models.TextField()
    date_commented = models.DateTimeField(default=timezone.now)
    issue = models.ForeignKey(Issue, related_name='comment', on_delete=models.CASCADE)
    critic = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=default_user)

    def __str__(self):
        return f"{self.issue} - {self.critic}"


class Query(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=default_user)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(max_length=100)
    description = models.TextField()
    open_date = models.DateTimeField(default=timezone.now)
    close_date = models.DateTimeField(blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.RESTRICT, default=Status.get_default_status)

    def __str__(self):
        return f"{self.category} - {self.title}"

    def get_absolute_url(self):
        return reverse('home')


class QueryComment(models.Model):
    comment = models.TextField()
    date_commented = models.DateTimeField(default=timezone.now)
    query = models.ForeignKey(Query, related_name='comment', on_delete=models.CASCADE)
    critic = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=default_user)

    def __str__(self):
        return f"{self.query} - {self.critic}"


class Feedback(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=default_user)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    date_actioned = models.DateTimeField(blank=True, null=True)
    actioned = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.category} - {self.description[:50]}"

    def get_absolute_url(self):
        return reverse('home')


class FeedbackComment(models.Model):
    comment = models.TextField()
    date_commented = models.DateTimeField(default=timezone.now)
    feedback = models.ForeignKey(Feedback, related_name='comment', on_delete=models.CASCADE)
    critic = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=default_user)

    def __str__(self):
        return f"{self.feedback} - {self.critic}"

support/forms.py
from django import forms
from . import models

class IssueCommentForm(forms.ModelForm):
    class Meta:
        model = models.IssueComment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 1}),
        }


class QueryCommentForm(forms.ModelForm):
    class Meta:
        model = models.QueryComment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 1}),
        }


class FeedbackCommentForm(forms.ModelForm):
    class Meta:
        model = models.FeedbackComment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 1}),
        }

support/templates/support/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_tags %}

{% block content %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group mb-0">
                <legend class="mb-0">
                    <h4 class="text-center">{{ legend }}</h4>
                </legend>
                <div class="row">
                    {% for field in form %}
                        <div class="{% if field.label|re_search:'Description|Title' %}col-sm-12{% else %}col-sm-6{% endif %}">
                            {{ field|as_crispy_field }}
                        </div>
                    {% endfor %}
                </div>
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-info px-5" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

support/templates/support/feedback_detail.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container my-2">
    <div class="row">
        <div class="col-sm-6">
            <h4>{{ object.category }} - {{ object.author.first_name }} {{ object.author.last_name }}</h4>
        </div>
        <div class="col-sm-6">
            <span class="text-muted float-right">{{ object.date_posted }}</span>
        </div>
    </div>
    <div class="row form-group-view">
        <textarea class="col-12 mx-3" readonly rows="{{ object.description|textarea_rows }}">{{ object.description }}</textarea>
    </div>
    {% if object.actioned %}
        <span class="float-right" style="color:green">Actioned on : {{ object.date_actioned }}</span>
    {% endif %}

    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'add_feedback_comment' object.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                <div class="col-md-11">
                    <fieldset class="form-group my-0">
                        <textarea name="comment" cols="40" rows="1" class="textarea form-control" required id="id_comment"></textarea>
                    </fieldset>
                </div>
                <div class="col-md-1 d-flex align-items-center">
                    <button class="btn btn-sm btn-info">Reply</button>
                </div>
            </div>
        </form>
    {% endif %}

    <h5 class="mx-3 mt-3" style="color:cadetblue;">
        All Messages ({{ object.comment.count }})
    </h5>
    <div class="border my-0">
        {% if not object.comment.all %}
            <div class="col-sm-6 text-muted">
                No Messages yet...
            </div>
        {% endif %}
        {% for comment in object.comment.all %}
            <div class="row text-muted mx-1 border-bottom">
                {% if comment.critic == object.author %}
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6">
                        <h6>
                            Author | {{ comment.date_commented }}
                        </h6>
                        <p class="update-para">{{ comment.comment }}</p>
                    </div>
                {% else %}
                    <div class="col-sm-6">
                        <h6>
                            {{ comment.critic.first_name }} {{ comment.critic.last_name }} ({{ comment.critic }}) |
                            {{ comment.date_commented }}
                        </h6>
                        <p class="update-para">{{ comment.comment }}</p>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

support/templates/support/issue_detail.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container my-2">
    {% if object.image %}
    <div class="row">
        <small class="mx-3">
            <span class="oi oi-link-intact"></span>
            <a href="{{ object.image.url }}" target="blank">{{ object.image }}</a>
        </small>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6">
            <div class="form-group-view my-2">
                <label class="col-sm-3">Requested By</label>
                <input class="col-sm-8" value="{{ object.author.first_name }} {{ object.author.last_name }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-3">Requestor ID</label>
                <input class="col-sm-8" value="{{ object.author }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-3">Category</label>
                <input class="col-sm-8" value="{{ object.category }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-3">Platform</label>
                <input class="col-sm-8" value="{{ object.platform }}" readonly />
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group-view my-2">
                <label class="col-sm-4">Request Open Date</label>
                <input class="col-sm-7" value="{{ object.create_date }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-4">Due Date (ETA)</label>
                <input class="col-sm-7" value="{{ object.due_date|default_if_none:'' }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-4">Request Close Date</label>
                <input class="col-sm-7" value="{{ object.close_date|default_if_none:'' }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-4">Priority</label>
                <input class="col-sm-7" value="{{ object.priority }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-4">Status</label>
                <input class="col-sm-7" value="{{ object.status }}" readonly />
            </div>
        </div>
    </div>

    <div class="row my-3 form-group-view">
        <label class="col-sm-3 mx-3">Short Description</label>
        <input class="col-sm-8 mx-3" value="{{ object.short_description }}" readonly />
    </div>

    <div class="row form-group-view">
        <label class="col-sm-3 mx-3" style="height: 33px;">Long Description</label>
        <textarea class="col-sm-8 mx-3" readonly rows="{{ object.long_description|textarea_rows }}">{{ object.long_description }}</textarea>
    </div>

    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'add_issue_comment' object.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                <div class="col-md-11">
                    <fieldset class="form-group my-0">
                        <textarea name="comment" cols="40" rows="1" class="textarea form-control" required id="id_comment"></textarea>
                    </fieldset>
                </div>
                <div class="col-md-1 d-flex align-items-center">
                    <button class="btn btn-sm btn-info">Reply</button>
                </div>
            </div>
        </form>
    {% endif %}

    <h5 class="mx-3 mt-3" style="color:cadetblue;">
        All Messages ({{ object.comment.count }})
    </h5>
    <div class="border my-0">
        {% if not object.comment.all %}
            <div class="col-sm-6 text-muted">
                No Messages yet...
            </div>
        {% endif %}
        {% for comment in object.comment.all %}
            <div class="row text-muted mx-1 border-bottom">
                {% if comment.critic == object.author %}
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6">
                        <h6>
                            Requester | {{ comment.date_commented }}
                        </h6>
                        <p class="update-para">{{ comment.comment }}</p>
                    </div>
                {% else %}
                    <div class="col-sm-6">
                        <h6>
                            {{ comment.critic.first_name }} {{ comment.critic.last_name }} ({{ comment.critic }}) |
                            {{ comment.date_commented }}
                        </h6>
                        <p class="update-para">{{ comment.comment }}</p>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

support/templates/support/query_detail.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container my-2">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group-view my-2">
                <label class="col-sm-3">Asked By</label>
                <input class="col-sm-8" value="{{ object.author.first_name }} {{ object.author.last_name }} ( {{ object.author }} )" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-3">Category</label>
                <input class="col-sm-8" value="{{ object.category }}" readonly />
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group-view my-2">
                <label class="col-sm-3">Open Date</label>
                <input class="col-sm-8" value="{{ object.open_date }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-3">Close Date</label>
                <input class="col-sm-8" value="{{ object.close_date|default_if_none:'' }}" readonly />
            </div>
            <div class="form-group-view my-2">
                <label class="col-sm-3">Status</label>
                <input class="col-sm-8" value="{{ object.status }}" readonly />
            </div>
        </div>
    </div>

    <div class="row my-3 form-group-view">
        <label class="col-sm-3 mx-3">Title</label>
        <input class="col-sm-8 mx-3" value="{{ object.title }}" readonly />
    </div>

    <div class="row form-group-view">
        <label class="col-sm-3 mx-3" style="height: 33px;">Description</label>
        <textarea class="col-sm-8 mx-3" readonly rows="{{ object.description|textarea_rows }}">{{ object.description }}</textarea>
    </div>

    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'add_query_comment' object.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                <div class="col-md-11">
                    <fieldset class="form-group my-0">
                        <textarea name="comment" cols="40" rows="1" class="textarea form-control" required id="id_comment"></textarea>
                    </fieldset>
                </div>
                <div class="col-md-1 d-flex align-items-center">
                    <button class="btn btn-sm btn-info">Reply</button>
                </div>
            </div>
        </form>
    {% endif %}

    <h5 class="mx-3 mt-3" style="color:cadetblue;">
        All Messages ({{ object.comment.count }})
    </h5>
    <div class="border my-0">
        {% if not object.comment.all %}
            <div class="col-sm-6 text-muted">
                No Messages yet...
            </div>
        {% endif %}
        {% for comment in object.comment.all %}
            <div class="row text-muted mx-1 border-bottom">
                {% if comment.critic == object.author %}
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6">
                        <h6>
                            Questioner | {{ comment.date_commented }}
                        </h6>
                        <p class="update-para">{{ comment.comment }}</p>
                    </div>
                {% else %}
                    <div class="col-sm-6">
                        <h6>
                            {{ comment.critic.first_name }} {{ comment.critic.last_name }} ({{ comment.critic }}) |
                            {{ comment.date_commented }}
                        </h6>
                        <p class="update-para">{{ comment.comment }}</p>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

support/templates/support/services.html
{% extends 'base.html' %}
{% load static %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/services.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content-section">
    <div class="row mt-1 px-3">
        <div class="col-sm-2">
            <div class="form-group mb-0">
                <label for="service_categories">Category</label>
                <select class="select form-control" id="service_categories">
                    {% for category in service_categories %}
                        <option value="{{category}}" {% if category == request.GET.category %}selected{% endif %}>{{category}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-sm-2">
            {% if legend == 'Reported Issues' or legend == 'All Queries' %}
                <div class="form-group mb-0">
                    <label for="service_statuses">Status</label>
                    <select class="select form-control" id="service_statuses">
                        {% for status in service_statuses %}
                            <option value="{{status}}" {% if status == request.GET.status %}selected{% endif %}>{{status}}</option>
                        {% endfor %}
                    </select>
                </div>
            {% endif %}
        </div>
        <div class="col-sm-2">
            {% if legend == 'Reported Issues' %}
                <div class="form-group mb-0">
                    <label for="service_priorities">Priority</label>
                    <select class="select form-control" id="service_priorities">
                        {% for priority in service_priorities %}
                            <option value="{{priority}}" {% if priority == request.GET.priority %}selected{% endif %}>{{priority}}</option>
                        {% endfor %}
                    </select>
                </div>
            {% endif %}
        </div>
        <div class="col-sm-6">
            <h4>
                {{ legend }} ( {{ objects.count }} )
                <a class="float-right pt-2 pr-3 text-decoration-none" href="{% url create_url %}" style="font-size: 18px;color: green;">
                    <span class="oi oi-plus"></span>
                </a>
            </h4>
        </div>
    </div>
    {% for object in objects %}
        <div class="card m-2" style="width: 100%;">
            <div class="card-body p-2">
                <div class="row">
                    <div class="col-sm-6">
                        <h5 class="card-title">{{ object.category }} |
                            {{ object.author.first_name }} {{ object.author.last_name }} ( {{ object.author }} )
                        </h5>
                    </div>
                    <div class="col-sm-6">
                        {% if legend == 'Reported Issues' %}
                            <span class="float-right">{{ object.create_date|date:"F d, Y" }}</span>
                        {% elif legend == 'All Queries' %}
                            <span class="float-right">{{ object.open_date|date:"F d, Y" }}</span>
                        {% elif legend == 'Suggestions / Feedback' %}
                            <span class="float-right">{{ object.date_posted|date:"F d, Y" }}</span>
                        {% endif %}
                    </div>
                </div>
                <h6 class="card-subtitle">
                    {% if legend == 'Reported Issues' %}
                        {{ object.short_description }}
                    {% elif legend == 'All Queries' %}
                        {{ object.title }}
                    {% endif %}
                </h6>
                <p class="card-text pt-2 pl-3">
                    {% if legend == 'Reported Issues' %}
                        {{ object.long_description|truncatechars:125 }}
                    {% elif legend == 'All Queries' %}
                        {{ object.description|truncatechars:125 }}
                    {% elif legend == 'Suggestions / Feedback' %}
                        {{ object.description|truncatechars:125 }}
                    {% endif %}
                </p>
                <div class="row">
                    <div class="col-sm-6">
                        <h6 style="color:cadetblue;">
                            <a href="{% url details_url object.id %}">All Messages ({{ object.comment.count }})</a>
                        </h6>
                    </div>
                    <div class="col-sm-6">
                        {% if user.is_superuser and object.status.name not in close_status_list and not object.actioned %}
                            <a class="btn btn-sm btn-outline-primary py-0 float-right" href="{% url update_url object.id %}">Update</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Privous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-{{ paginate_by ]}}' and num < page_obj.number|add:'{{ paginate_by }}' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

support/templates/support/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_tags %}

{% block content %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group mb-0">
                <div class="row border-bottom my-2">
                    <div class="col-sm-6">
                        <h4>
                            {{ object.category }} | {{ object.author.first_name }} {{ object.author.last_name }} ( {{ object.author }} )
                        </h4>
                    </div>
                    <div class="col-sm-6">
                        <span class="text-muted float-right">{{ object.create_date }}</span>
                        <span class="text-muted float-right">{{ object.open_date }}</span>
                        <span class="text-muted float-right">{{ object.date_posted }}</span>
                    </div>
                </div>
                {% if object.image %}
                    <div class="row mb-2">
                        <small class="mx-3">
                            <span class="oi oi-link-intact"></span>
                            <a href="{{ object.image.url }}" target="blank">{{ object.image }}</a>
                        </small>
                    </div>
                {% endif %}
                {% if legend == 'Issue' %}
                    <div class="row my-3 form-group-view">
                        <label class="col-sm-3 mx-3">Platform</label>
                        <input class="col-sm-8 mx-3" value="{{ object.platform }}" readonly />
                    </div>
                    <div class="row my-3 form-group-view">
                        <label class="col-sm-3 mx-3">Short Description</label>
                        <input class="col-sm-8 mx-3" value="{{ object.short_description }}" readonly />
                    </div>
                    <div class="row form-group-view">
                        <label class="col-sm-3 mx-3" style="height: 33px;">Long Description</label>
                        <textarea class="col-sm-8 mx-3" readonly rows="{{ object.long_description|textarea_rows }}">{{ object.long_description }}</textarea>
                    </div>
                {% elif legend == 'Query' %}
                    <div class="row my-3 form-group-view">
                        <label class="col-sm-3 mx-3">Title</label>
                        <input class="col-sm-8 mx-3" value="{{ object.title }}" readonly />
                    </div>
                    <div class="row form-group-view">
                        <label class="col-sm-3 mx-3" style="height: 33px;">Description</label>
                        <textarea class="col-sm-8 mx-3" readonly rows="{{ object.description|textarea_rows }}">{{ object.description }}</textarea>
                    </div>
                {% elif legend == 'Feedback' %}
                    <div class="row form-group-view">
                        <label class="col-sm-3 mx-3" style="height: 33px;">Description</label>
                        <textarea class="col-sm-8 mx-3" readonly rows="{{ object.description|textarea_rows }}">{{ object.description }}</textarea>
                    </div>
                {% endif %}
                <div class="row mt-5">
                    <div class="col-sm-12">
                        <h6 style="color:cadetblue;">
                            <a href="{% url details_url object.id %}">All Messages ({{ object.comment.count }})</a>
                        </h6>
                    </div>
                </div>
                <div class="row border-top mt-1">
                    {% for field in form %}
                        <div class="{% if field.label|re_search:'Description|Title' %}col-sm-12{% else %}col-sm-6{% endif %}">
                            {{ field|as_crispy_field }}
                        </div>
                    {% endfor %}
                </div>
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-info px-5" type="submit" {% if object.status.name in close_status_list or object.actioned %}disabled{% endif %}>
                    Update {{ legend }}
                </button>
            </div>
        </form>
    </div>
{% endblock %}